Update automate.yml

diff --git a/.github/workflows/automate.yml b/.github/workflows/automate.yml
--- a/.github/workflows/automate.yml
+++ b/.github/workflows/automate.yml
@@ -1,66 +1,197 @@
-name: Test
+name: Program workflow
 
 on:
   push:
-    branches: [ "main" ]
+    branches:
+      - main
   pull_request:
-    branches: [ "main" ]
+    branches:
+      - main
 
 permissions:
   contents: write
 
 jobs:
-  build:
-
+  autopep8:
+    name: Autopep8
     runs-on: ubuntu-latest
-
+    env:
+      PYTHONPATH: ${{ github.workspace }}
     steps:
-    - uses: actions/checkout@v4
-    - name: Set up Python 3.x
-      uses: actions/setup-python@v3
-      with:
-        python-version: "3.x"
+      - uses: actions/checkout@v3
 
-    - name: Install coreutils (for shuf command)
-      run: sudo apt-get install coreutils
+      - uses: actions/setup-python@v4
+        with:
+          python-version: '3.12'
 
-    - name: Install dependencies
-      run: |
-        python -m pip install --upgrade pip
-        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
-        pip install codecov
-    
-    - name: Analysing the code with autopep8
-      run: |
-        autopep8 --in-place --recursive hw2_debugging.py rand.py
+      - run: |
+          python -m pip install --upgrade pip
+          pip install autopep8
 
-    - name: Analysing the code with pylint
-      run: |
-        pylint hw2_debugging.py rand.py
-        
-    - name: Analysing the code with flake8
-      run: |
-        flake8 hw2_debugging.py rand.py
-    
-    - name: Analysing the code with radon
-      run: |
-        radon cc hw2_debugging.py rand.py
+      - name: Run autopep8
+        run: autopep8 --in-place --recursive .
 
-    - name: Run test cases
-      run: |
-        pytest -v tests/
+  pylint:
+    name: Pylint
+    runs-on: ubuntu-latest
+    needs: autopep8
+    env:
+      PYTHONPATH: ${{ github.workspace }}
+    steps:
+      - uses: actions/checkout@v3
 
-    - name: Test the cases
-      run: | 
-        pytest --cov=. --cov-report=term --cov-report=json:coverage.json # to test all cases with code coverage and report to terminal as well as to coverage.json file
-    
-    - name: Upload coverage to Codecov
-      uses: codecov/codecov-action@v3
-      with:
-        token: ${{ secrets.CODECOV_TOKEN }}
-        files: ./coverage.json
+      - uses: actions/setup-python@v4
+        with:
+          python-version: '3.12'
 
-   
+      - run: |
+          python -m pip install --upgrade pip
+          pip install pylint
 
-    # - name: Generate coverage badge
-    #   uses: we-cli/coverage-badge-action@main
+      - id: pylint
+        run: pylint **/*.py
+        continue-on-error: true
+
+  coverage:
+    name: Code Coverage
+    runs-on: ubuntu-latest
+    env:
+      PYTHONPATH: ${{ github.workspace }}
+    needs: [autopep8, pylint]
+    steps:
+      - uses: actions/checkout@v3
+
+      - uses: actions/setup-python@v4
+        with:
+          python-version: '3.12'
+
+      - run: |
+          python -m pip install --upgrade pip
+          pip install pytest pytest-cov
+
+      - run: |
+          pytest --cov=source --cov-report xml
+        continue-on-error: true
+
+      - name: Upload coverage report
+        uses: actions/upload-artifact@v3
+        with:
+          name: coverage-report
+          path: coverage.xml
+
+  generate-badges:
+    name: Generate Badges
+    runs-on: ubuntu-latest
+    needs: coverage
+    env:
+      PYTHONPATH: ${{ github.workspace }}
+    steps:
+      - uses: actions/checkout@v3
+
+      - name: Download coverage report
+        uses: actions/download-artifact@v3
+        with:
+          name: coverage-report
+
+      - name: Install dependencies
+        run: |
+          sudo apt-get update
+          sudo apt-get install -y libxml2-utils
+          python -m pip install --upgrade pip
+          pip install pylint pytest pytest-cov
+
+      - name: Generate badge URLs
+        id: generate_badges
+        run: |
+          pylint_output=$(pylint **/*.py 2>&1) || true
+          pylint_exit_code=$?
+          echo "Pylint exit code: $pylint_exit_code"
+          echo "Pylint output: $pylint_output"
+          
+          pylint_score=$(echo "$pylint_output" | grep -oP '(?<=rated at )\d+\.\d+' | tail -1)
+          pylint_score=${pylint_score:-0}
+          echo "Pylint score: $pylint_score"
+          
+          exit_code_pylint=1
+          if (( $(echo "$pylint_score < 5" | bc -l) )) || [ $pylint_exit_code -ne 0 ]; then
+            pylint_color="red"
+            exit_code_pylint=0
+          elif (( $(echo "$pylint_score < 10" | bc -l) )); then
+            pylint_color="orange"
+            exit_code_pylint=0
+          else
+            pylint_color="green"
+          fi
+          pylint_badge="https://img.shields.io/badge/pylint-${pylint_score}-${pylint_color}"
+          echo "Pylint badge: $pylint_badge"
+
+          pytest_output=$(pytest --cov=source --cov-report xml 2>&1) || true
+          exit_code_pytest=1
+          echo "Pytest exit code: $pytest_exit_code"
+          echo "Pytest output: $pytest_output"
+          
+          if [ -f coverage.xml ]; then
+            coverage=$(xmllint --xpath "string(//coverage/@line-rate)" coverage.xml)
+            coverage_percentage=$(echo "scale=0; $coverage * 100" | bc)
+            if (( $(echo "$coverage_percentage >= 97" | bc -l) )); then
+              coverage_color="green"
+            elif (( $(echo "$coverage_percentage >= 90" | bc -l) )); then
+              exit_code_pytest=0
+              coverage_color="orange"
+            else
+              exit_code_pytest=0
+              coverage_color="red"
+            fi
+          else
+            coverage_percentage="0"
+            coverage_color="red"
+          fi
+          coverage_badge="https://img.shields.io/badge/coverage-${coverage_percentage}%25-${coverage_color}"
+          echo "Coverage badge: $coverage_badge"
+
+          if echo "$pytest_output" | grep -q "FAILURES"; then
+            test_status="failing"
+            test_color="red"
+          else
+            test_status="passing"
+            test_color="green"
+          fi
+          test_badge="https://img.shields.io/badge/tests-${test_status}-${test_color}"
+          echo "Test badge: $test_badge"
+
+          echo "pylint_badge=$pylint_badge" >> $GITHUB_ENV
+          echo "coverage_badge=$coverage_badge" >> $GITHUB_ENV
+          echo "test_badge=$test_badge" >> $GITHUB_ENV
+
+      - name: Update README with badges
+        env:
+          RUN_URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
+        run: |
+          sed -i '/\[Test Coverage: pytest-cov\]/c\[![Test Coverage: pytest-cov](${{ env.coverage_badge }})](${{ env.RUN_URL }})' README.md
+          sed -i '/\[Pylint\]/c\[![Pylint](${{ env.pylint_badge }})](${{ env.RUN_URL }})' README.md
+          sed -i '/\[Tests\]/c\[![Tests](${{ env.test_badge }})](${{ env.RUN_URL }})' README.md
+
+      - name: Commit and push changes
+        uses: EndBug/add-and-commit@v9
+        with:
+          author_name: git
+          author_email: git@example.com
+          message: Update badges in README
+
+  check-status:
+    name: Check Status
+    needs: [pylint, coverage, generate-badges]
+    runs-on: ubuntu-latest
+    if: always()
+    steps:
+      - name: Check job status
+        run: |
+          for prog in pylint pytest; do
+            EXIT_CODE_VAR="exit_code_${prog}"
+            EXIT_CODE="${!EXIT_CODE_VAR}"
+            echo "Checking exit code for $prog: $EXIT_CODE"
+            if [ "$EXIT_CODE" == 0 ]; then
+              echo "$prog failed, marking job as failed."
+              exit 1
+            fi
+          done
